"""initial schema

Revision ID: 5fc19af729fc
Revises: 
Create Date: 2026-03-09 10:10:12.696411
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '5fc19af729fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_dividends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.String(length=4), nullable=False),
    sa.Column('dividend_per_share', sa.Float(), nullable=False),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('payout_ratio', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'fiscal_year', 'provider', name='uq_dividend_symbol_year_provider')
    )
    op.create_index('idx_dividend_symbol', 'company_dividends', ['symbol'], unique=False)
    op.create_table('company_financials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corp_code', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('operating_income', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('total_equity', sa.BigInteger(), nullable=True),
    sa.Column('total_debt', sa.BigInteger(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('pbr', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corp_code', 'period', 'provider', name='uq_financial_corp_period_provider')
    )
    op.create_index('idx_financial_corp_code', 'company_financials', ['corp_code'], unique=False)
    op.drop_table('kiwoom_service_keys')
    op.add_column('heartbeats', sa.Column('broker_connected', sa.Boolean(), nullable=True))
    op.drop_column('heartbeats', 'kiwoom_connected')
    op.add_column('stock_master', sa.Column('corp_code', sa.String(length=10), nullable=True))
    op.create_index('idx_stock_corp_code', 'stock_master', ['corp_code'], unique=False)
    op.add_column('trading_rules', sa.Column('script', sa.Text(), nullable=True))
    op.add_column('trading_rules', sa.Column('execution', sa.JSON(), nullable=True))
    op.add_column('trading_rules', sa.Column('trigger_policy', sa.JSON(), nullable=True))
    op.add_column('trading_rules', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_rules', 'priority')
    op.drop_column('trading_rules', 'trigger_policy')
    op.drop_column('trading_rules', 'execution')
    op.drop_column('trading_rules', 'script')
    op.drop_index('idx_stock_corp_code', table_name='stock_master')
    op.drop_column('stock_master', 'corp_code')
    op.add_column('heartbeats', sa.Column('kiwoom_connected', sa.BOOLEAN(), nullable=True))
    op.drop_column('heartbeats', 'broker_connected')
    op.create_table('kiwoom_service_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('api_secret', sa.VARCHAR(length=512), nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_financial_corp_code', table_name='company_financials')
    op.drop_table('company_financials')
    op.drop_index('idx_dividend_symbol', table_name='company_dividends')
    op.drop_table('company_dividends')
    # ### end Alembic commands ###
